export const formInit = ({
    profileTypes = [],
    roles = [],
    onUpdateType = () => {},
}) => {
    return [
        {
            key: "profile_type",
            label: "Tipo de perfil",
            type: "combobox",
            required: true,
            itemTitle: "name",
            itemValue: "id",
            options: profileTypes,
            onUpdate: onUpdateType,
            cols: 12,
            default: null,
        },
        {
            key: "profile_id",
            label: "Perfil",
            type: "combobox",
            required: true,
            itemTitle: "name",
            itemValue: "id",
            options: [],
            onUpdate: () => {},
            cols: 12,
            default: null,
        },
        {
            key: "email",
            label: "Email",
            type: "text",
            required: true,
            cols: 12,
            default: "",
        },
        {
            key: "password",
            label: "Contraseña",
            type: "password",
            required: true,
            cols: 12,
            default: "",
        },
        {
            key: "role",
            label: "Rol",
            type: "combobox",
            required: true,
            itemTitle: "name",
            itemValue: "id",
            colMd: 12,
            default: null,
            onUpdate: () => {},
            options: roles,
        },
        {
            key: "is_enabled",
            label: "Activo",
            type: "checkbox",
            required: true,
            colMd: 12,
            default: true,
        },
    ];
};
